# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overe < Formula
  desc "A background app to record audio via a hotkey and transcribe it."
  homepage "https://github.com/kennyparsons/overe"
  version "1.2.3"
  license "MIT"

  depends_on "kennyparsons/go-transcribe/go-transcribe"
  depends_on :macos

  on_arm do
    url "https://github.com/kennyparsons/overe/releases/download/v1.2.3/overe_Darwin_arm64.tar.gz"
    sha256 "f967d8da7ae3599ac35d851b54ba9fcd91c22fbcb7e4a5e0edf2e1cd9995d929"

    def install
      bin.install "overe"
    end
  end

  service do
    run [opt_bin/"overe"]
    keep_alive true
    run_at_load true
  end
end
