# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overe < Formula
  desc "A background app to record audio via a hotkey and transcribe it."
  homepage "https://github.com/kennyparsons/overe"
  version "1.2.2"
  license "MIT"

  depends_on "kennyparsons/go-transcribe/go-transcribe"
  depends_on :macos

  on_arm do
    url "https://github.com/kennyparsons/overe/releases/download/v1.2.2/Overe_Darwin_arm64.tar.gz"
    sha256 "1872b47380fe07d977627beb3b6492af6953c075ee3445abe049ee9758930d98"

    def install
      bin.install "Overe"
    end
  end

  service do
    run [opt_bin/"Overe"]
    keep_alive true
    run_at_load true
  end
end
